export const CITY_DATABASE = [
  'Provinsi Nanggroe Aceh Darussalam', 'Provinsi Sumatera Utara', 'Provinsi Sumatera Barat', 'Provinsi Riau', 'Provinsi Kepulauan Riau', 'Provinsi Jambi', 'Provinsi Sumatera Selatan', 'Provinsi Kepulauan Bangka Belitung', 'Provinsi Bengkulu', 'Provinsi Lampung', 'Provinsi DKI Jakarta', 'Provinsi Banten', 'Provinsi Jawa Barat', 'Provinsi Jawa Tengah', 'Provinsi DI Yogyakarta', 'Provinsi Jawa Timur', 'Provinsi Bali', 'Provinsi Nusa Tenggara Barat', 'Provinsi Nusa Tenggara Timur', 'Provinsi Kalimantan Barat', 'Provinsi Kalimantan Tengah', 'Provinsi Kalimantan Selatan', 'Provinsi Kalimantan Timur', 'Provinsi Kalimantan Utara', 'Provinsi Sulawesi Utara', 'Provinsi Gorontalo', 'Provinsi Sulawesi Tengah', 'Provinsi Sulawesi Barat', 'Provinsi Sulawesi Selatan', 'Provinsi Sulawesi Tenggara', 'Provinsi Maluku', 'Provinsi Maluku Utara', 'Provinsi Papua', 'Provinsi Papua Barat', 'Provinsi Papua Selatan', 'Provinsi Papua Tengah', 'Provinsi Papua Pegunungan', 'Provinsi Papua Barat Daya',
  'Jakarta Pusat', 'Jakarta Selatan', 'Jakarta Barat', 'Jakarta Timur', 'Jakarta Utara', 'Kepulauan Seribu', 'Kota Bogor', 'Kab. Bogor', 'Kota Depok', 'Kota Tangerang', 'Kota Tangerang Selatan', 'Kab. Tangerang', 'Kota Bekasi', 'Kab. Bekasi', 'Kota Serang', 'Kab. Serang', 'Kota Cilegon', 'Kab. Lebak', 'Kab. Pandeglang',
  'Kota Bandung', 'Kab. Bandung', 'Kab. Bandung Barat', 'Kota Cimahi', 'Kota Sukabumi', 'Kab. Sukabumi', 'Kota Cirebon', 'Kab. Cirebon', 'Kota Tasikmalaya', 'Kab. Tasikmalaya', 'Kota Banjar', 'Kab. Garut', 'Kab. Ciamis', 'Kab. Pangandaran', 'Kab. Kuningan', 'Kab. Majalengka', 'Kab. Sumedang', 'Kab. Indramayu', 'Kab. Subang', 'Kab. Purwakarta', 'Kab. Karawang', 'Kab. Cianjur',
  'Kota Semarang', 'Kab. Semarang', 'Kota Salatiga', 'Kota Magelang', 'Kab. Magelang', 'Kota Surakarta (Solo)', 'Kab. Boyolali', 'Kab. Klaten', 'Kab. Sukoharjo', 'Kab. Wonogiri', 'Kab. Karanganyar', 'Kab. Sragen', 'Kab. Grobogan', 'Kab. Blora', 'Kab. Rembang', 'Kab. Pati', 'Kab. Kudus', 'Kab. Jepara', 'Kab. Demak', 'Kab. Temanggung', 'Kab. Wonosobo', 'Kab. Purworejo', 'Kab. Kebumen', 'Kab. Cilacap', 'Kab. Banyumas (Purwokerto)', 'Kab. Purbalingga', 'Kab. Banjarnegara', 'Kota Tegal', 'Kab. Tegal', 'Kab. Brebes', 'Kab. Pemalang', 'Kota Pekalongan', 'Kab. Pekalongan', 'Kab. Batang', 'Kab. Kendal', 'Kota Yogyakarta', 'Kab. Sleman', 'Kab. Bantul', 'Kab. Gunungkidul', 'Kab. Kulon Progo',
  'Kota Surabaya', 'Kab. Sidoarjo', 'Kab. Gresik', 'Kab. Mojokerto', 'Kota Mojokerto', 'Kab. Jombang', 'Kab. Bojonegoro', 'Kab. Tuban', 'Kab. Lamongan', 'Kota Madiun', 'Kab. Madiun', 'Kab. Ngawi', 'Kab. Magetan', 'Kab. Ponorogo', 'Kab. Pacitan', 'Kota Kediri', 'Kab. Kediri', 'Kab. Nganjuk', 'Kab. Trenggalek', 'Kab. Tulungagung', 'Kota Blitar', 'Kab. Blitar', 'Kota Malang', 'Kab. Malang', 'Kota Batu', 'Kab. Lumajang', 'Kab. Jember', 'Kab. Banyuwangi', 'Kab. Bondowoso', 'Kab. Situbondo', 'Kota Probolinggo', 'Kab. Probolinggo', 'Kota Pasuruan', 'Kab. Pasuruan', 'Kab. Bangkalan', 'Kab. Sampang', 'Kab. Pamekasan', 'Kab. Sumenep',
  'Kota Banda Aceh', 'Kota Medan', 'Kab. Deli Serdang', 'Kota Pematangsiantar', 'Kota Binjai', 'Kota Padang', 'Kota Bukittinggi', 'Kota Pekanbaru', 'Kota Dumai', 'Kota Batam', 'Kota Tanjungpinang', 'Kota Jambi', 'Kota Palembang', 'Kab. Banyuasin', 'Kota Pangkalpinang', 'Kota Bengkulu', 'Kota Bandar Lampung', 'Kota Metro',
  'Kota Pontianak', 'Kota Singkawang', 'Kota Palangka Raya', 'Kota Banjarmasin', 'Kota Banjarbaru', 'Kota Balikpapan', 'Kota Samarinda', 'Kota Bontang', 'Kota Tarakan', 'Kab. Kutai Kartanegara',
  'Kota Makassar', 'Kab. Gowa', 'Kab. Maros', 'Kota Parepare', 'Kota Palopo', 'Kota Manado', 'Kota Bitung', 'Kota Tomohon', 'Kota Gorontalo', 'Kota Palu', 'Kota Kendari', 'Kota Bau-Bau',
  'Kota Denpasar', 'Kab. Badung', 'Kab. Gianyar', 'Kab. Buleleng (Singaraja)', 'Kab. Tabanan', 'Kota Mataram', 'Kab. Lombok Barat', 'Kab. Lombok Tengah', 'Kab. Lombok Timur', 'Kota Kupang', 'Kab. Manggarai Barat (Labuan Bajo)',
  'Kota Ambon', 'Kota Ternate', 'Kota Jayapura', 'Kab. Jayapura', 'Kab. Mimika (Timika)', 'Kab. Merauke', 'Kota Sorong', 'Kab. Manokwari',
  'Remote', 'Work From Anywhere (WFA)'
];

export const mockHistoryList = [];
